### ISSUE TITLE
Stack not clear yet Event loop kicks in

### ISSUE THREAD

**Issue by innokria** [latentflip/loupe#22]
console.log('first call');
setTimeout(function timeout() {
    console.log("second call");
}, 5000);
alert('a')
setTimeout(function tim() {
    console.log("second scoend call");
}, 2000);

console.log("third call");

_______________________________
Note: alert call is still in stack but then event loop kicks in and execute timeout

**Comment by latentflip** [comment]
It's tripping up on `alert` which is unsupported in the runtime.
