### ISSUE TITLE
different results for setTimeout

### ISSUE THREAD

**Issue by minahalim** [latentflip/loupe#9]
console.log("first call");

setTimeout(function cp1() {
    console.log("second call");
}, 1000);

setTimeout(function cp2() {
    console.log("third call");
}, 0);

console.log("fourth  call");

I have tried this code in the console and it's giving me different results from the one in loupe

Chrome Console:
first call
fourth call
third call
second call

Loupe Console:
first call
fourth call
second call
third call

**Comment by minahalim** [comment]
Got the answer from another issue already closed... thanks

**Comment by sanketmaru** [comment]
@mino20032 Can you share from which issue you got the answer for this ?

**Comment by minahalim** [comment]
@sanketmaru for the late respond, I got it from this issue: https://github.com/latentflip/loupe/issues/8
